// Re-export specific types to avoid conflicts
export type {
  // Common types
  BaseEntity,
  Coordinates,
  BoundingBox,
  Dimensions,
  Position,
  Size,
  Color,
  DateRange,
  TimeRange,
  PaginationParams,
  SortParams,
  FilterParams,
  SearchParams,
  TelecomCompany,
  NetworkTechnology,
  FrequencyBand,
  TowerStatus,
  InfrastructureType,
  SignalQuality,
  CoverageType,
  UserRole,
  Permission,
  IndianState,
  Region,
  UrbanClassification,
  Environment,
  AppMode,
  DeploymentMode,
  DataQuality,
  ValidationRule,
  FileFormat,
  ExportFormat,
  FileMetadata,
  ImportConfig,
  PerformanceMetrics,
  HealthStatus,
  FeatureFlag,
  AppConfiguration,
  EventType,
  AuditEvent,
} from './common.types';

export type {
  // Auth types
  User,
  UserPreferences,
  NotificationType as AuthNotificationType,
  LoginCredentials,
  LoginResponse as AuthLoginResponse,
  AuthState,
  TokenPayload,
  RegisterCredentials,
  PasswordResetRequest as AuthPasswordResetRequest,
  PasswordResetConfirm,
  ChangePasswordRequest,
  Session,
  ActiveSession,
  RoleDefinition,
  PermissionDefinition,
  UserGroup,
  MFASetup,
  MFAVerification,
  MFASettings,
  OAuthProvider,
  SSOConfiguration,
  Company,
  UserInvitation,
  LoginAttempt,
  SecurityEvent,
  ProfileUpdateRequest,
  AvatarUploadResponse,
} from './auth.types';

export type {
  // Map types
  MapInstance,
  MapViewport,
  MapConfiguration,
  MapOptions,
  CustomMapControl,
  MapControlState,
  MapMarker,
  MarkerType,
  MarkerIcon,
  InfoWindowData,
  DrawnShape,
  ShapeType,
  ShapeStyle,
  DrawingManagerState,
  MapLayer,
  LayerType,
  LayerSource,
  LayerStyle,
  LayerFilter,
  ClusteringConfig,
  ClusterStyle,
  HeatmapConfig,
  SearchResult as MapSearchResult,
  GeocodingResult,
  SearchConfiguration,
  RouteRequest,
  RouteResult,
  RouteInfo,
  RouteLeg,
  RouteStep,
  MeasurementResult,
  ElevationData,
  Geofence,
  GeofenceTrigger,
  GeofenceAction,
  StreetViewData,
  MapPerformanceConfig,
  MapStats,
} from './map.types';

export type {
  // Data types
  TelecomTower,
  TowerEquipment,
  AntennaDetails,
  ComplianceCertificate,
  SafetyMeasure,
  TowerPerformance,
  BackhaulConnection,
  NetworkCoverage,
  SignalQualityData,
  CoverageQualityMetrics,
  CapacityMetrics,
  InterferenceSource,
  DriveTestResult,
  DataImportJob,
  ValidationError as DataValidationError,
  ValidationWarning,
  DataExportJob,
  DataFilter,
  SearchQuery,
  SearchResult as DataSearchResult,
  DataQualityReport,
  DataQualityRecommendation,
  BulkOperation,
} from './data.types';

export type {
  // UI types
  UIState,
  ThemeType,
  ThemeConfig,
  ThemeColors,
  ColorPalette,
  SemanticColors,
  SurfaceColors,
  TextColors,
  BorderColors,
  ThemeFonts,
  ThemeSpacing,
  ThemeShadows,
  ThemeAnimations,
  LayoutState,
  SidebarState,
  HeaderState,
  FooterState,
  WorkspaceState,
  WorkspaceConfig,
  ComponentConfig,
  ResponsiveState,
  NavigationState,
  Breadcrumb,
  MenuItem,
  NavigationHistory,
  ModalState,
  Modal,
  ModalType,
  ModalSize,
  ModalPosition,
  ModalOptions,
  NotificationState,
  Notification,
  NotificationType as UINotificationType,
  NotificationPosition,
  NotificationAction,
  PanelState,
  Panel,
  PanelOptions,
  PanelBounds,
  LoadingState as UILoadingState,
  GlobalLoading,
  ComponentLoading,
  OperationLoading,
  PerformanceState,
  PerformanceMetrics as UIPerformanceMetrics,
  PerformanceAlert,
  FormState,
  FormConfig,
  FormField,
  InputType,
  SelectOption,
  FieldValidation,
  FormValidation,
  ValidationRule as UIValidationRule,
  AutoSaveConfig,
  AccessibilityState,
  Announcement,
  FocusManagement,
  SkipLink,
  KeyboardNavigation,
  KeyboardShortcut,
  ScreenReaderConfig,
} from './ui.types';

export type {
  // Analytics types
  AnalyticsMetric,
  MetricCategory,
  MetricType,
  AggregationType,
  TimeSeriesData,
  TimeSeriesMetric,
  TimeGranularity,
  PerformanceMetrics as AnalyticsPerformanceMetrics,
  SystemPerformance,
  ApplicationPerformance,
  NetworkPerformance,
  UserExperienceMetrics,
  BusinessMetrics,
  RevenueMetrics,
  CostMetrics,
  ROIMetrics,
  MarketMetrics,
  MarketTrend,
  CustomerMetrics,
  NetworkAnalytics,
  CoverageAnalytics,
  CoverageGap,
  QualityAnalytics,
  QualityIssue,
  CapacityAnalytics,
  CapacityBottleneck,
  ExpansionNeed,
  UtilizationAnalytics,
  EfficiencyOpportunity,
  IncidentAnalytics,
  Report,
  ReportType,
  ReportCategory,
  ReportFormat,
  ReportSchedule,
  ReportFilters,
  ReportStatus,
  ChartConfiguration,
  ChartType,
  DataSource,
  AxisConfiguration,
  SeriesConfiguration,
  ChartStyling,
  ChartInteractions,
  TableConfiguration,
  TableColumn,
  TablePagination,
  TableSorting,
  TableFiltering,
  TableStyling,
  Alert,
  AlertType,
  AlertSeverity,
  AlertStatus,
  AlertCondition,
  AlertNotification,
  DataExport,
} from './analytics.types';

export type {
  // API types
  ApiResponse,
  ApiError as APIError,
  ApiMeta,
  PaginatedResponse,
  SearchResponse as APISearchResponse,
  FacetResult,
  ApiConfig,
  RequestOptions,
  LoginRequest,
  LoginResponse as APILoginResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  PasswordResetRequest as APIPasswordResetRequest,
  PasswordResetResponse,
  PasswordResetConfirmRequest,
  GetTowersRequest,
  CreateTowerRequest,
  UpdateTowerRequest,
  BulkTowerOperationRequest,
  BulkTowerOperationResponse,
  GetCoverageRequest,
  CoverageAnalysisRequest,
  CoverageAnalysisResponse,
  GetAnalyticsRequest,
  AnalyticsData,
  GetAnalyticsResponse,
  CreateReportRequest,
  GenerateReportRequest,
  GenerateReportResponse,
  ImportDataRequest,
  ImportDataResponse,
  ExportDataRequest,
  ExportDataResponse,
  WebSocketMessage,
  SubscriptionRequest,
  SubscriptionResponse,
  FileUploadRequest,
  FileUploadResponse,
  MultipartUploadRequest,
  MultipartUploadResponse,
  HealthCheckResponse,
  ServiceHealth,
  SystemMetricsResponse,
  RateLimitInfo,
  RateLimitResponse,
  WebhookConfig,
  WebhookPayload,
  WebhookDelivery,
  ApiEndpoint,
  ApiParameter,
  ApiRequestBody,
  ApiErrorDetails,
  ValidationErrorResponse,
  CacheConfig,
  CacheStrategy,
  CacheStats,
} from './api.types';